# Generated by Django 3.2.6 on 2021-08-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20210831_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='uploaded_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
