# Generated by Django 3.2.6 on 2021-08-31 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_alter_song_uploaded_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Track duration ins seconds'),
        ),
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(upload_to='audio', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'wma', 'amr'])]),
        ),
    ]
