# Generated by Django 3.2.6 on 2021-08-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20210831_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
