# Generated by Django 3.2.6 on 2021-09-01 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_alter_song_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
