# Generated by Django 3.2.6 on 2021-09-01 09:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_alter_song_uploaded_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='uploaded_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 1, 9, 0, 3, 460700, tzinfo=utc)),
        ),
    ]
